[tool.poetry]
name = "daffy"
version = "0.3.0"
description = "Function decorators for Pandas Dataframe column name and data type validation"
authors = ["Janne Sinivirta <janne.sinivirta@gmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/fourkind/daffy"
repository = "https://github.com/fourkind/daffy.git"
keywords = ["pandas", "dataframe", "typing", "validation"]
classifiers = [
    "Operating System :: OS Independent",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Software Development :: Quality Assurance",
    "Intended Audience :: Developers",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Development Status :: 4 - Beta",
    "License :: OSI Approved :: MIT License"
]
include = [
    "LICENSE",
]

[tool.poetry.dependencies]
python = "^3.7.1"
pandas = "^1.2.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
isort = "^5.7.0"
black = "^20.8b1"
flake8 = "^3.8.4"
pre-commit = "^2.10.0"
mypy = "^0.800"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"
multi_line_output = 3
